spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  port: 9999
  servlet:
    context-path: /

services:
  mongodb:
    host: 192.168.60.20
    port: 27017
    database: VUEJS
    username: vuejs
    password: vuejs12#$
  influxdb:
    url: http://192.168.60.20:8086
    token: opennaru12#$
    org: openmaru
    bucket: VUEJS
    max-connections: 10
    wait-idle-close-ttl: 60000
    request-timeout: 30000
    session-timeout: 60000
  hazelcast:
    cluster-name: vuejs-cluster
    address: 127.0.0.1
    port: 5701
  rabbitmq:
    host: 192.168.60.20
    port: 5672
    username: khan
    password: opennaru12#$
    exchange-name: vue.direct
    queue-name: vue.queue
    routing-key: vue.key

vuejs:
  rest-url: http://localhost:8080